name: Clip

on:
  workflow_dispatch:
      inputs:
        video_url:
          description: "Video url:"
          required: true
        start_time:
          description: "Clip start time:(hh:mm:ss)"
          required: true
        end_time:
          description: "Clip end time:"
          required: true

permissions:
  contents: read

jobs:
  clip:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: Set up POT provider
      run: |
        docker run --name bgutil-provider -d -p 4416:4416 brainicism/bgutil-ytdlp-pot-provider


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp --pre
        pip install -U bgutil-ytdlp-pot-provider
        sudo apt update&&sudo apt install ffmpeg -y
        mkdir output
    - name: Get Clip
      run: |
        python3 ./main.py --url  "${{ github.event.inputs.video_url }}" --start ${{ github.event.inputs.start_time }} --end ${{ github.event.inputs.end_time }}
    - uses: actions/upload-artifact@v4
      with:
        name: output
        path: output
